# Generated by Django 4.0.4 on 2022-04-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0003_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='byrthday',
            new_name='birthday',
        ),
    ]
